name: Executar srcipt de temperatures Manresa
on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositori
        uses: actions/checkout@v3

      - name: Configuració Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.11'

      - name: Instal·lar dependències
        run: |
          pip install requests

      - name: Executar script de temperatures
        run: |
          python obtenir_temperatures.py


